// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_zF-JeO5LjyN4TUJ5dDgDjpTNxkYi17A',
    appId: '1:773701534582:web:fd2851a8256b110e573057',
    messagingSenderId: '773701534582',
    projectId: 'waterwise-499e5',
    authDomain: 'waterwise-499e5.firebaseapp.com',
    storageBucket: 'waterwise-499e5.firebasestorage.app',
    measurementId: 'G-J3MHBY1Q73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF2INIOzkscy-2s_dgQMzGaM1VM5BECIY',
    appId: '1:773701534582:android:8a55a18d95cc82aa573057',
    messagingSenderId: '773701534582',
    projectId: 'waterwise-499e5',
    storageBucket: 'waterwise-499e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc24Opk95lNms6ox7QvjtY1DTejxkW6WA',
    appId: '1:773701534582:ios:869f68135d34777b573057',
    messagingSenderId: '773701534582',
    projectId: 'waterwise-499e5',
    storageBucket: 'waterwise-499e5.firebasestorage.app',
    iosBundleId: 'com.example.waterwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc24Opk95lNms6ox7QvjtY1DTejxkW6WA',
    appId: '1:773701534582:ios:869f68135d34777b573057',
    messagingSenderId: '773701534582',
    projectId: 'waterwise-499e5',
    storageBucket: 'waterwise-499e5.firebasestorage.app',
    iosBundleId: 'com.example.waterwise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_zF-JeO5LjyN4TUJ5dDgDjpTNxkYi17A',
    appId: '1:773701534582:web:3c03670c89078fc3573057',
    messagingSenderId: '773701534582',
    projectId: 'waterwise-499e5',
    authDomain: 'waterwise-499e5.firebaseapp.com',
    storageBucket: 'waterwise-499e5.firebasestorage.app',
    measurementId: 'G-N7MREGP9X9',
  );
}
